# NumPy Basic Exercises
In this notebook, I practice the fundamentals of NumPy arrays, including creation, slicing, and basic operations.

1. arr.shape --> tell us about shape of data
2. arr.size  --> tell us about the numbers of elements
3. arr.ndim  --> tell us about the no. of dimensions
4. arr.shape[0]  --> give no of rows
5. arr.shape[1] ---> give no of cols

NOTE : arr.shape[1] one will workonly when your array dimensions is   2-d,otherwise it will throw error

implementations is below!!!

In [1]:
import numpy as np
arr=np.array([[10, 20],
 [30, 40],
 [50, 60]])
print('the shape of 2-d array is \n : ',arr.shape)  # shape of data
print(f"the dimensions of the 2-d array is \n  : {arr.ndim}") # dimensions of data
print(f"the size of the 2-d array is {arr.size}")  # no of elements in data
print(f"the shape zero in brackets is \n  {arr.shape[0]}") # give no of rows
print(f"the shape one in brackers is ]n  {arr.shape[1]}")   # give no of cols
arr=np.array([1,2,3,4,5,6])
print('the shape of 2-d array is \n : ',arr.shape) # shape of data
print(f"the dimensions of the 2-d array is \n  : {arr.ndim}") # dimensions of data
print(f"the size of the 2-d array is {arr.size}")  # no of elements in data
print(f"the shape zero in brackets is \n  {arr.shape[0]}") # give no of rows



the shape of 2-d array is 
 :  (3, 2)
the dimensions of the 2-d array is 
  : 2
the size of the 2-d array is 6
the shape zero in brackets is 
  3
the shape one in brackers is ]n  2
the shape of 2-d array is 
 :  (6,)
the dimensions of the 2-d array is 
  : 1
the size of the 2-d array is 6
the shape zero in brackets is 
  6


# RESHAPING
first find out the original shape before reshaping
Reshaping convert 1d to 2d and 3d and vice versa
for reshaping we use
1. arr.reshape() # function
  i.e:
  ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
  sh=ar.reshape(3,4) # it will convert 1d to 2d array
  print(sh)
2. reshaping will be allowed when no. of rows * mo. of cols==no.of  elements
In the above example qd array has 12 elements then in reshaping 3 (rows) * 4 (cols) =12
3. reshape(-1,1)
    it figure out the rows automatically without specifically mentioning, it calculate row like
    no. of elements /no. of col = no. of rows
4. converting to  (2, 2, 3) → 3D → multiple tables stacked on top of each other , fisrt '2' is layers second '2' is rows third '3' is column
5. to convert back to 1d ,
 reshape(-1)
6. to convert from 3d to 2d:
Collapse the last two dimensions: arr_3d.reshape(arr_3d.shape[0], -1)
For a (2, 3, 4) array, this results in a (2, 12) shape.
Using reshape(-1): arr_2d.reshape(-1)

implementations is below!!


In [2]:
import numpy as np
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ar)
print(f"shape of array : {ar.shape}")
# RESHAPING AN ARRAY .....1d to 2d
sh=ar.reshape(3,4)
print(sh)
print(f"shape of array : {sh.shape}")
# RESHAPING AN ARRAY .....1d to 2d
sh=ar.reshape(4,3)
print(sh)
print(sh.shape)
print("The last exercise output.....")
# RESHAPING AN ARRAY .....to 3d
sh=ar.reshape(2,2,3)
print(sh)
print(sh.shape)
arr=np.arange(1,13)
# RESHAPING AN ARRAY .....
result=arr.reshape(-1,2)
print(result)
print(result.shape)
# RESHAPING IN 3D IS
r2=arr.reshape(2,2,3)
print(r2)
print(r2.shape)
print(f"the n-dimension of an 3d array is {r2.ndim}")



[ 1  2  3  4  5  6  7  8  9 10 11 12]
shape of array : (12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape of array : (3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
The last exercise output.....
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
(6, 2)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
the n-dimension of an 3d array is 3


--------------SLICING IN NUMPY--------------
------------1D ARRAY----------------------
arr[0] → grab element at index 0
arr[-1] → -1 always means last element,
-2 means second last, and so on
arr[1:4] → start at index 1,
stop before index 4 arr[:3] → no start means begin from 0
arr[2:] → no end means go till the last element
 -----------2D ARRAY-------------------------
 arr2d[row, column] → always row first, column second
 arr2d[1, 2] → go to row 1 → [4, 5, 6] → grab column 2 → 6
 arr2d[0:2, :] → rows 0 to 1, : means all columns arr2d[:, 1] → : means all rows, only column 1



In [3]:
import numpy as np
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
arr = np.array([100, 200, 300, 400, 500])
print(f"Grabbing the 3rd element : {arr[2]}")
print(f"Grabbing the 2nd element : {arr[1]}")
print(f"Grabbing the last 2 elements : {arr[-2:]}")
print(f"Grabbing the value 60 from data : {data[1, 2]}")
print(f"Grabbing the enitre second col of data : {data[:, 1]}")


Grabbing the 3rd element : 300
Grabbing the 2nd element : 200
Grabbing the last 2 elements : [400 500]
Grabbing the value 60 from data : 60
Grabbing the enitre second col of data : [20 50 80]


Num - py built-in functions
np.zeros --. fill all arrays with zeros
np.ones  --> fill all arrays with ones
np.arange(start, stop, step) → like Python's range() but returns a NumPy array start=0, stop=10, step=2 → begin at 0, go up by 2, stop before 10 Stop is never included
np.linspace(start, stop, num) → gives num evenly spaced values between start and stop ** Unlike arange, stop is included** linspace(0, 1, 5) → 5
 in simple way,
 arange → you control the specified step size
linspace → you control the number of points
np.random.rand(3, 3) → 3×3 array of random floats between 0 and 1 np.random.randint(0, 100, (3, 3)) → 3×3 array of random integers between 0 and 99

In [4]:
import numpy as np
arr=np.zeros((4,4))
print(" zeros : ",arr)
print(f'the shape of zeros is {arr.shape} \n the dimensions is : {arr.ndim}')
arr=np.arange(1,20,3)
print(f'the values are : {arr}')
arr=np.linspace(0,5,6)
print(f'six evenly spaced values between 0 and 5 are : {arr}')
arr=np.random.randint(1,50,(3,3))
print(f'random int numbers are : {arr}')

 zeros :  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
the shape of zeros is (4, 4) 
 the dimensions is : 2
the values are : [ 1  4  7 10 13 16 19]
six evenly spaced values between 0 and 5 are : [0. 1. 2. 3. 4. 5.]
random int numbers are : [[35 13 48]
 [44 30 21]
 [ 4  8  6]]


Num-py numericalstatiscal functions
np.sum() → adds every element together
np.min() → finds the smallest element
np.max() → finds the largest element

np.mean() → sum divided by count = average
np.std() → how spread out values are from the mean. Small std = values close together, large std = values scattered
np.var() → std squared.
Another measure of spread np.median() → middle value when sorted. Here (15+16)/2 = 15.5

np.sum(arr2d) → adds all elements regardless of shape
 axis=0 → operate down the rows (column-wise) → 1+4=5, 2+5=7, 3+6=9 axis=1 → operate across the columns (row-wise) → 1+2+3=6, 4+5+6=15

np.argmax() → doesn't return the max value, returns its index position np.argmin() → same but for minimum value 42 is at index 5 → argmax = 5 4 is at index 0 → argmin = 0

In [5]:
arr = np.array([3, 7, 1, 9, 4, 6, 8, 2])
print(arr)
print(np.sum(arr))
print(f"the max and min value is : {np.max(arr)} , {np.min(arr)} \n their indexes are {np.argmax(arr)} , {np.argmin(arr)}")
print(np.mean(arr))
data = np.array([[10, 20, 30],
                 [40, 50, 60]])
print(f"the max and min value is : {np.max(data)} , {np.min(data)} \n their indexes are {np.argmax(data)} , {np.argmin(data)}")
print(f'the sum of each column is : {np.sum(data, axis=0)}')
print(f'the sum of each row is : {np.sum(data, axis=1)}')


[3 7 1 9 4 6 8 2]
40
the max and min value is : 9 , 1 
 their indexes are 3 , 2
5.0
the max and min value is : 60 , 10 
 their indexes are 5 , 0
the sum of each column is : [50 70 90]
the sum of each row is : [ 60 150]


boolean and filtering....
In real ML projects, your data is messy. You need to filter out specific values — like finding all students who scored above 50, or removing all negative values from a dataset. Boolean masking lets you do this in one clean line. It's used constantly in data preprocessing.

In [6]:
arr = np.array([5, 12, 3, 18, 7, 25, 9, 30])
print(f'greater than 10 {arr[arr>10]}')
print(f"values between 5 & 20 {arr[(arr>=5) & (arr<=20)]}")
arr[arr>20]=0
print(f'replacing all values with 0 greater than 20 {arr}')
# Exercise 4: A student passes if score ≥ 50. Print only the passing scores.
scores = np.array([45, 82, 31, 90, 55, 70, 48, 95])
passs=scores[scores>=50]
print(f'passing students with passing scores are \n {passs}')
test=np.array([999,-999,999])
test[test==-999]=0
print(test)

greater than 10 [12 18 25 30]
values between 5 & 20 [ 5 12 18  7  9]
replacing all values with 0 greater than 20 [ 5 12  3 18  7  0  9  0]
passing students with passing scores are 
 [82 90 55 70 95]
[999   0 999]
