# ---- --- Student Score Management System (NumPy Mini Project)-------

This project demonstrates how to use **NumPy** for data analysis.
We are managing a dataset of **8 students** and their marks in **3 subjects** (Math, Science, English).
I apply everything from Lesson 1 together to achieve each tasks which are given below:

Task 1: Print the shape of the dataset. How many students and subjects?
Task 2: Print the scores of the 3rd student (index 2).
Task 3: Print the scores of all students in Math only (column 0).
Task 4: Find the highest and lowest score in the entire dataset.
Task 5: Find the average score per student (mean across each row).
Task 6: Find the average score per subject (mean across each column).
Task 7: A student passes if their average score ≥ 60. Print the averages of passing students only.
Task 8: Reshape the entire scores array into shape (4, 6). Print the new shape.

### Key Features:
- Statistical Analysis (Mean, Max, Min)
- Data Slicing & Indexing
- Boolean Filtering (Finding passing students)
- Data Reshaping


In [6]:
# ----MINI PROJECT---
import numpy as np

# 8 students, 3 subjects (Math, Science, English)
scores = np.array([[55, 72, 68],
                   [90, 85, 88],
                   [42, 38, 50],
                   [78, 80, 75],
                   [95, 92, 97],
                   [30, 45, 40],
                   [65, 70, 60],
                   [88, 79, 83]])
# 1. Row & Column Analysis with specific slicing
print(f'the shape of data set {scores.shape}\nthe no. of students : {scores.shape[0]} \nthe no. of subjects : {scores.shape[1]} \n')
score=scores[2:3,:]
print(f'the score of third student :  {score.reshape(-1)} \n') # cleaned to back 1D
print(f'the score of all students in Math only : {scores[:,:1].reshape(-1)} \n') # again cleaned to back 1d
print(f'the highest and lowest score in  dataset is {np.max(scores)} , {np.min(scores)} \n')
print(f'the avg score of each student  is {np.mean(scores, axis=1)} \n') # statiscal calculations
print(f'the avg score of each subject is {np.mean(scores, axis=0)} \n')  # statiscal calculations

# 4. Boolean Filtering (Passing Criteria >=60)
avg_marks=np.mean(scores, axis=1)
passed_std=scores[avg_marks>=60]
avg_passed_std=np.mean(passed_std, axis=1)
print(f"the students who passed are \n {passed_std} \n and their averages ara {avg_passed_std} \n")
scores=scores.reshape(4,6)
print(f"the reshaping of score into 4 x 6 \n {scores}")

the shape of data set (8, 3)
the no. of students : 8 
the no. of subjects : 3 

the score of third student :  [42 38 50] 

the score of all students in Math only : [55 90 42 78 95 30 65 88] 

the highest and lowest score in  dataset is 97 , 30 

the avg score of each student  is [65.         87.66666667 43.33333333 77.66666667 94.66666667 38.33333333
 65.         83.33333333] 

the avg score of each subject is [67.875 70.125 70.125] 

the students who passed are 
 [[55 72 68]
 [90 85 88]
 [78 80 75]
 [95 92 97]
 [65 70 60]
 [88 79 83]] 
 and their averages ara [65.         87.66666667 77.66666667 94.66666667 65.         83.33333333] 

the reshaping of score into 4 x 6 
 [[55 72 68 90 85 88]
 [42 38 50 78 80 75]
 [95 92 97 30 45 40]
 [65 70 60 88 79 83]]
